#pragma once

enum KsCommand : uint16_t {
    // GROUNDSTATION COMMANDS
    KS_CMD_PING,
    KS_CMD_TLE,
    KS_CMD_ECHO,
    KS_CMD_ECHO_TLM,
    KS_CMD_DOWNLINK_BEGIN,
    KS_CMD_DOWNLINK_FETCH,
    KS_CMD_DOWNLINK_CONTINUE,
    KS_CMD_LIST_FILES,
    KS_CMD_LIST_TLM_GROUPS,
    KS_CMD_LIST_TLM_CHANNELS,

    // SATELLITE COMMANDS
    KS_CMD_RES_FILEINFO,
    KS_CMD_RES_FILES,
    KS_CMD_RES_FILEPART,
    KS_CMD_RES_TLM_GROUPS,
    KS_CMD_RES_TLM_CHANNELS,

    KS_CMD_END__,
};
