#pragma once

enum KsCommand : uint16_t {
    // GROUNDSTATION COMMANDS
    KS_CMD_PING,
    KS_CMD_TLE,
    KS_CMD_ECHO,
    KS_CMD_DOWNLINK_BEGIN,
    KS_CMD_DOWNLINK_FETCH,
    KS_CMD_DOWNLINK_CONTINUE,
    KS_CMD_LIST_FILES,

    // SATELLITE COMMANDS
    KS_CMD_RES_FILEINFO,
    KS_CMD_RES_FILES,
    KS_CMD_RES_FILEPART,

    KS_CMD_END__,
};
